lzc-sdk-version: 0.1
name: TestENV
package: ink.akawa.ety001.testenv
version: 0.0.1
description: For personal use.
author: ety001
min_os_version: 1.3.8
application:
  subdomain: testenv
  background_task: false
  multi_instance: false
  gpu_accel: true
  usb_accel: true
  ingress:
    - protocol: tcp
      port: 22
      service: testenv
  routes:
    - /=http://testenv.ink.akawa.ety001.testenv.lzcapp:10000
services:
  testenv:
    # ety001/xpra-base:ubuntu-noble
    image: registry.lazycat.cloud/ety001/ety001/xpra-base:ebd8c86acea1c8c7
    shm_size: "512m"
    tmpfs:
      - /run
    environment:
      - XDG_RUNTIME_DIR=/run/user/1001
    binds:
      - /lzcapp/var/home:/home/lzc
      - /lzcapp/var/home_ssh:/home/lzc/.ssh
      - /lzcapp/var/home_config:/home/lzc/.config
      - /lzcapp/cache/home_cache:/home/lzc/.cache
      - /lzcapp/cache/supervisor:/var/log/supervisor
    setup_script: /lzcapp/pkg/content/init.sh