lzc-sdk-version: "0.1"
package: ink.akawa.ety001.jellyfinme
version: 10.10.6
name: Jellyfin Me
description: 由 ETY001 封装的 Jellyfin，主要是把网络改为了 HOST
homepage: https://jellyfin.org/
author: Jellyfin
application:
  gpu_accel: true
  background_task: true
  user_app: true
  routes:
    - /=http://jellyfin.ink.akawa.ety001.jellyfinme.lzcapp:8096
  depends_on:
    - jellyfin
  subdomain: jellyfinme
services:
  jellyfin:
    #image: linuxserver/jellyfin:10.10.6
    image: registry.lazycat.cloud/ety001/linuxserver/jellyfin:d550c06870254f34
    network_mode: "host"
    environment:
      - OAUTH2_ENABLE=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=${LAZYCAT_AUTH_OIDC_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}
      - OAUTH2_SERVER_URL=${LAZYCAT_AUTH_OIDC_ISSUER_URL}
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/run/mnt/home:/home
