lzc-sdk-version: "0.1"
package: ink.akawa.ety001.jellyfinme
version: 10.10.6
name: Jellyfin Me
description: 由 ETY001 封装的 Jellyfin，主要是把网络改为了 HOST
homepage: https://jellyfin.org/
#homepage: https://github.com/ety001/lzc-appdb/tree/master/jellyfin-me
author: Jellyfin
application:
  gpu_accel: true
  background_task: true
  user_app: true
  routes:
    - /=http://jellyfin.ink.akawa.ety001.jellyfinme.lzcapp:8096
  depends_on:
    - jellyfin
  subdomain: jellyfinme
services:
  jellyfin:
    #image: linuxserver/jellyfin:10.10.6
    image: registry.lazycat.cloud/ety001/linuxserver/jellyfin:d550c06870254f34
    network_mode: "host"
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/run/mnt/home:/home
