lzc-sdk-version: 0.1
name: pgAdmin4
package: ink.akawa.ety001.pgadmin
version: 0.0.1
description: pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL
license: https://www.pgadmin.org/docs/pgadmin4/latest/licence.html
homepage: https://www.pgadmin.org/
author: pgadmin
min_os_version: 1.3.0
application:
  subdomain: pgadmin
  background_task: true
  multi_instance: false
  routes:
    - /=http://pgadmin.ink.akawa.ety001.pgadmin.lzcapp:80
services:
  pgadmin:
    image: registry.lazycat.cloud/ety001/dpage/pgadmin4:72d1f53329fb844b
    environment:
      - PGADMIN_DEFAULT_EMAIL=pg@lzc.cloud
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DISABLE_POSTFIX=1
      - PGADMIN_CUSTOM_CONFIG_DISTRO_FILE=/config/config_distro.py
      - PGADMIN_CONFIG_AUTHENTICATION_SOURCES=['internal']
      #- PGADMIN_CONFIG_OAUTH2_NAME='LazyCat'
      #- PGADMIN_CONFIG_OAUTH2_DISPLAY_NAME='LazyCat'
      #- PGADMIN_CONFIG_OAUTH2_CLIENT_ID='${LAZYCAT_AUTH_OIDC_CLIENT_ID}'
      #- PGADMIN_CONFIG_OAUTH2_CLIENT_SECRET='${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}'
      #- PGADMIN_CONFIG_OAUTH2_TOKEN_URL='${LAZYCAT_AUTH_OIDC_ISSUER_URL}/token'
      #- PGADMIN_CONFIG_OAUTH2_AUTHORIZATION_URL='${LAZYCAT_AUTH_OIDC_ISSUER_URL}/authorize'
      #- PGADMIN_CONFIG_OAUTH2_API_BASE_URL='${LAZYCAT_AUTH_OIDC_ISSUER_URL}'
      #- PGADMIN_CONFIG_OAUTH2_ICON='fa-cat'
      #- PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER=True
    binds:
      - /lzcapp/var/pgadmin:/var/lib/pgadmin
      - /lzcapp/var/config:/config
    setup_script: |
      #!/bin/bash
      #whoami
      chown -R 5050:5050 /var/lib/pgadmin
      chown -R 5050:5050 /config
locales:
  zh:
    description: "pgAdmin 是世界上最流行和功能最丰富的开源管理和开发平台，是世界上最先进的开源数据库。"
  zh_CN:
    description: "pgAdmin 是世界上最流行和功能最丰富的开源管理和开发平台，是世界上最先进的开源数据库。"
  en:
    description: "pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world."