application:
  subdomain: tiejiastorm
  routes:
    - /=http://tiejiastorm.ink.akawa.ety001.tiejiastorm.lzcapp:6080

services:
  tiejiastorm:
    image: registry.lazycat.cloud/ety001/ety001/tiejiafengbao:10edc5a000b0cc67
