ext_config:
  enable_document_access: true
  enable_media_access: true
application:
  subdomain: lzcmobile
  background_task: true
  multi_instance: false
  usb_accel: true
  oidc_redirect_path: /auth/oidc/callback
  routes:
    - /=http://lzcmobile.ink.akawa.ety001.lzcmobile.lzcapp:8071
  ingress:
    - protocol: tcp
      description: SIP通信端口
      port: 5060
      service: lzcmobile
    - protocol: udp
      description: SIP通信端口
      port: 5060
      service: lzcmobile
    - protocol: udp
      description: RTP通信端口
      service: lzcmobile
      publish_port: 40890-40920
services:
  lzcmobile:
    image: registry.lazycat.cloud/ety001/ety001/lzc-mobile:ecdc136f0ac96b26
    #image: dev.ecat.heiyu.space/ety001/lzc-mobile:1774085383
    network_mode: host
    environment:
      - WEB_PORT=8071
      - DB_PATH=/var/lib/lzc-mobile/data.db
      - ASTERISK_CONFIG_DIR=/etc/asterisk
      - ASTERISK_TEMPLATE_DIR=/app/configs/asterisk
      - ASTERISK_LOG_PATH=/var/log/asterisk/full
      - LAZYCAT_AUTH_BASE_URL=https://${LAZYCAT_APP_DOMAIN}
      - LAZYCAT_AUTH_OIDC_CLIENT_ID=${LAZYCAT_AUTH_OIDC_CLIENT_ID}
      - LAZYCAT_AUTH_OIDC_CLIENT_SECRET=${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}
      - LAZYCAT_AUTH_OIDC_AUTH_URI=${LAZYCAT_AUTH_OIDC_AUTH_URI}
      - LAZYCAT_AUTH_OIDC_TOKEN_URI=${LAZYCAT_AUTH_OIDC_TOKEN_URI}
      - LAZYCAT_AUTH_OIDC_USERINFO_URI=${LAZYCAT_AUTH_OIDC_USERINFO_URI}
      - ASTERISK_AMI_USERNAME=admin
      - ASTERISK_AMI_PASSWORD={{ stable_secret "admin_password" }}
    binds:
      - /lzcapp/var/data:/var/lib/lzc-mobile/
      - /lzcapp/var/logs:/var/log/asterisk/
