application:
  public_path:
    - /hooks
  subdomain: webhook
  background_task: true
  multi_instance: true
  routes:
    - /=http://webhook:8080

services:
  webhook:
    image: registry.lazycat.cloud/ety001/ety001/linglong-webhook:1bf8e137556e1397
    runtime: sysbox-runc
    binds:
      - /lzcapp/var/conf:/data/conf
      - /lzcapp/var/workspace:/data/workspace
      - /lzcapp/var/docker:/var/lib/docker
    environment:
      - TZ=Asia/Shanghai
      - LZC_ENCRYPTION_KEY={{ .U.encryption_key }}
