application:
  public_path:
    - /hooks
  subdomain: webhook
  background_task: true
  multi_instance: true
  routes:
    - /=http://webhook:8080
  injects:
    - id: open-save-chooser
      on: browser
      when:
        - /*
      do:
        - src: file:///lzcapp/pkg/content/lazycat-injects/lzc-file-chooser-inject.js
          params:
            locale: auto
            hooks:
              fileSystemAccess: true
              fileInput: true

services:
  webhook:
    image: registry.lazycat.cloud/ety001/ety001/linglong-webhook:96705c81c9996a13
    runtime: sysbox-runc
    binds:
      - /lzcapp/var/conf:/data/conf
      - /lzcapp/var/workspace:/data/workspace
      - /lzcapp/var/docker:/var/lib/docker
    environment:
      - TZ=Asia/Shanghai
      - LZC_ENCRYPTION_KEY={{ .U.encryption_key }}
