FROM debian:bookworm-slim

ARG REPOFILE=https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/bookworm/xpra-lts.sources

RUN apt update -y && \
    apt upgrade -y && \
    apt install -y ca-certificates wget gpg openssh-server supervisor vim && \
    wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra.asc && \
    cd /etc/apt/sources.list.d && wget $REPOFILE && \
    apt update -y && \
    DEBIAN_FRONTEND=noninteractive apt install -y xserver-xorg xpra && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
ADD ./sshd.conf /etc/supervisor/conf.d/sshd.conf

EXPOSE 10000

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
