application:
  subdomain: drone
  background_task: true
  multi_instance: false
  routes:
    - /=http://drone-server.ink.akawa.ety001.drone-ci.lzcapp:80
services:
  drone-server:
    image: registry.lazycat.cloud/ety001/drone/drone:c1bd209e337bae09
    binds:
      - /lzcapp/var/data:/data
    environment:
      # Gogs
      - DRONE_GOGS_SERVER={{ .U.gogs_server }}
      # GitHub
      - DRONE_GITHUB_CLIENT_ID={{ .U.github_client_id }}
      - DRONE_GITHUB_CLIENT_SECRET={{ .U.github_client_secret }}
      # GitLab
      - DRONE_GITLAB_CLIENT_ID={{ .U.gitlab_client_id }}
      - DRONE_GITLAB_CLIENT_SECRET={{ .U.gitlab_client_secret }}
      # Gitea
      - DRONE_GITEA_SERVER={{ .U.gitea_server }}
      - DRONE_GITEA_CLIENT_ID={{ .U.gitea_client_id }}
      - DRONE_GITEA_CLIENT_SECRET={{ .U.gitea_client_secret }}
      # Bitbucket
      - DRONE_BITBUCKET_CLIENT_ID={{ .U.bitbucket_client_id }}
      - DRONE_BITBUCKET_CLIENT_SECRET={{ .U.bitbucket_client_secret }}
      # Common
      - DRONE_RPC_SECRET={{ stable_secret "rpc_secret" }}
      - DRONE_SERVER_HOST={{ .S.AppDomain }}
      - DRONE_SERVER_PROTO=https
      - DRONE_USER_CREATE=username:{{ .U.admin_user }},admin:true
  drone-runner:
    image: registry.lazycat.cloud/ety001/ety001/drone-runner-docker:dfac963834868ea6
    runtime: sysbox-runc
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server.ink.akawa.ety001.drone-ci.lzcapp
      - DRONE_RPC_SECRET={{ stable_secret "rpc_secret" }}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=my-first-runner
