lzc-sdk-version: 0.1
name: Zettlr
package: ink.akawa.ety001.zettlr
version: 3.5.1
description: For personal use.
author: zettlr
min_os_version: 1.3.8
application:
  subdomain: zettlr
  background_task: false
  multi_instance: false
  gpu_accel: true
  usb_accel: true
  ingress:
    - protocol: tcp
      port: 22
      service: zettlr
  routes:
    - /=http://zettlr.ink.akawa.ety001.zettlr.lzcapp:10000
services:
  zettlr:
    # ety001/zettlr:ubuntu-noble
    image: registry.lazycat.cloud/ety001/ety001/zettlr:89a28658debf5e48
    shm_size: "512m"
    tmpfs:
      - /run
    environment:
      - XDG_RUNTIME_DIR=/run/user/1001
    binds:
      - /lzcapp/var/home:/home/lzc
      - /lzcapp/var/home_ssh:/home/lzc/.ssh
      - /lzcapp/var/home_config:/home/lzc/.config
      - /lzcapp/cache/home_cache:/home/lzc/.cache
      - /lzcapp/cache/supervisor:/var/log/supervisor
    setup_script: /lzcapp/pkg/content/init.sh