lzc-sdk-version: 0.1
name: AppFlowy
package: ink.akawa.ety001.appflowy
version: 0.0.1
description: AppFlowy is the AI collaborative workspace where you achieve more without losing control of your data.
license: https://github.com/AppFlowy-IO/AppFlowy-Web#AGPL-3.0-1-ov-file
homepage: https://www.appflowy.io/
author: appflowy
min_os_version: 1.3.0
application:
  subdomain: appflowy
  background_task: true
  multi_instance: false
  routes:
    - /=http://web:80
    - /api/=http://appflowy:8000/api/
    - /gotrue/=http://gotrue:9999/
    - /minio/=http://minio:9000/minio/
services:
  appflowy:
    image: registry.lazycat.cloud/ety001/appflowy/appflowy:5d080eb56344e617
    environment:
      - RUST_LOG=info
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_DATABASE_URL=postgres://postgres:123456@timescaledb:5432/postgres
      - APPFLOWY_REDIS_URI=redis://redis:6379
      - APPFLOWY_GOTRUE_JWT_SECRET=hello456
      - APPFLOWY_GOTRUE_BASE_URL=http://gotrue:9999
      - APPFLOWY_S3_CREATE_BUCKET=true
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=http://minio:9000
      - APPFLOWY_S3_ACCESS_KEY=minioadmin
      - APPFLOWY_S3_SECRET_KEY=minioadmin
      - APPFLOWY_S3_BUCKET=appflowy
      - APPFLOWY_S3_REGION=us-east-1
      - APPFLOWY_ACCESS_CONTROL=true
      - APPFLOWY_DATABASE_MAX_CONNECTIONS=40
      - AI_SERVER_HOST=ai
      - AI_SERVER_PORT=5001
      - APPFLOWY_WEB_URL=http://web:80
      - APPFLOWY_BASE_URL=http://appflowy.ink.akawa.ety001.appflowy.lzcapp
    depends_on:
      - timescaledb
      - redis
      - minio
      - gotrue
  
  timescaledb:
    image: registry.lazycat.cloud/ety001/timescale/timescaledb:a7eb4b43d24c842e
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    binds:
      - /lzcapp/var/pgdata:/var/lib/postgresql/data
    health_check:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-h", "localhost"]
      start_period: 60s

  redis:
    image: redis:7.2
    environment:
      - TZ=Asia/Shanghai
  
  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    environment:
      - MINIO_BROWSER_REDIRECT_URL=http://appflowy.ink.akawa.ety001.appflowy.lzcapp/minio
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    binds:
      - /lzcapp/var/minio:/data

  gotrue:
    image: appflowyinc/gotrue:2.132.3
    environment:
      - GOTRUE_ADMIN_EMAIL=admin@example.com
      - GOTRUE_ADMIN_PASSWORD=password
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_SITE_URL=appflowy-flutter://
      - GOTRUE_URI_ALLOW_LIST=**
      - GOTRUE_JWT_SECRET=hello456
      - GOTRUE_JWT_EXP=604800
      - GOTRUE_JWT_ADMIN_GROUP_NAME=supabase_admin
      - GOTRUE_DB_DRIVER=postgres
      - API_EXTERNAL_URL=http://appflowy.ink.akawa.ety001.appflowy.lzcapp/gotrue
      - DATABASE_URL=postgres://postgres:123456@timescaledb:5432/postgres?search_path=auth
      - PORT=9999
      - GOTRUE_MAILER_URLPATHS_CONFIRMATION=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_INVITE=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_RECOVERY=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=/gotrue/verify
      - GOTRUE_MAILER_AUTOCONFIRM=true
    depends_on:
      - timescaledb

  worker:
    image: appflowyinc/appflowy_worker:0.5.6
    environment:
      - RUST_LOG=info
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_WORKER_REDIS_URL=redis://redis:6379
      - APPFLOWY_WORKER_ENVIRONMENT=production
      - APPFLOWY_WORKER_DATABASE_URL=postgres://postgres:123456@timescaledb:5432/postgres
      - APPFLOWY_WORKER_DATABASE_NAME=postgres
      - APPFLOWY_WORKER_IMPORT_TICK_INTERVAL=30
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=http://minio:9000
      - APPFLOWY_S3_ACCESS_KEY=minioadmin
      - APPFLOWY_S3_SECRET_KEY=minioadmin
      - APPFLOWY_S3_BUCKET=appflowy
      - APPFLOWY_S3_REGION=us-east-1
    depends_on:
      - timescaledb
      - redis
      - minio

  web:
    image: appflowyinc/appflowy_web:0.5.8
    environment:
      - APPFLOWY_BASE_URL=http://appflowy.ink.akawa.ety001.appflowy.lzcapp
      - APPFLOWY_GOTRUE_BASE_URL=http://appflowy.ink.akawa.ety001.appflowy.lzcapp/gotrue
      - APPFLOWY_WS_BASE_URL=ws://appflowy.ink.akawa.ety001.appflowy.lzcapp/ws/v2
    depends_on:
      - appflowy

  ai:
    image: appflowyinc/appflowy_ai:0.3.6
    environment:
      - AI_SERVER_PORT=5001
      - DEFAULT_AI_MODEL=gpt-4.1-mini
      - DEFAULT_AI_COMPLETION_MODEL=gpt-4.1-mini
      - APPFLOWY_S3_ACCESS_KEY=minioadmin
      - APPFLOWY_S3_SECRET_KEY=minioadmin
      - APPFLOWY_S3_BUCKET=appflowy
      - APPFLOWY_S3_REGION=us-east-1
      - AI_DATABASE_URL=postgres://postgres:123456@timescaledb:5432/postgres
      - AI_REDIS_URL=redis://redis:6379
      - AI_USE_MINIO=true
      - AI_MINIO_URL=http://minio:9000
      - AI_APPFLOWY_HOST=http://appflowy.ink.akawa.ety001.appflowy.lzcapp
      - APPFLOWY_GOTRUE_JWT_SECRET=hello456
    depends_on:
      - timescaledb
      - redis
      - minio

locales:
  zh:
    description: "AppFlowy是AI协作工作空间, 让你在数据控制中实现更多."
  zh_CN:
    description: "AppFlowy是AI协作工作空间, 让你在数据控制中实现更多."
  en:
    description: "AppFlowy is the AI collaborative workspace where you achieve more without losing control of your data."