lzc-sdk-version: 0.1
name: Banbot
package: ink.akawa.ety001.banbot
version: 0.2.16
description: Banbot is a high-performance, easy-to-use, multi-symbol, multi-strategy, multi-period, multi-account event-driven trading robot.
license: https://github.com/banbox/banbot?tab=AGPL-3.0-1-ov-file#readme
homepage: https://www.banbot.site/
author: banbot
#  /_lzc/sys/verify_usage
usage: |
  配置文件在应用数据目录下的 data 目录下, 配置方法参见 banbot 官方文档, https://www.banbot.site。
min_os_version: 1.3.0
application:
  subdomain: banbot
  background_task: true
  multi_instance: false
  routes:
    - /=http://banbot.ink.akawa.ety001.banbot.lzcapp:8000
services:
  banbot:
    # banbot/banbot:v0.2.16
    image: registry.lazycat.cloud/ety001/banbot/banbot:4dc1d43e832070f3
    environment:
      - BanDataDir=/ban/data
      - BanStratDir=/ban/strats
    depends_on:
      - timescaledb
    binds:
      - /lzcapp/var/data:/ban/data
      - /lzcapp/var/strats:/ban/strats
    entrypoint: /lzcapp/pkg/content/init.sh
  timescaledb:
    # timescale/timescaledb:latest-pg17
    image: registry.lazycat.cloud/ety001/timescale/timescaledb:ba98ce0e319c7e06
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=123456
    binds:
      - /lzcapp/var/pgdata:/var/lib/postgresql/data
      - /lzcapp/var/pg_healthcheck_log:/var/log/healthcheck
    health_check:
      test: ["CMD-SHELL", "/lzcapp/pkg/content/healthcheck.sh"]
      start_period: 180s
locales:
  zh:
    description: "Banbot是一款高性能、易用的多币种、多策略、多周期、多账户事件驱动交易机器人"
    usage: |
      配置文件在应用数据目录下的 data 目录下, 配置方法参见 banbot 官方文档, https://www.banbot.site。
  zh_CN:
    description: "Banbot是一款高性能、易用的多币种、多策略、多周期、多账户事件驱动交易机器人"
    usage: |
      配置文件在应用数据目录下的 data 目录下, 配置方法参见 banbot 官方文档, https://www.banbot.site。
  en:
    description: "Banbot is a high-performance, easy-to-use, multi-symbol, multi-strategy, multi-period, multi-account event-driven trading robot"
    usage: |
      The config file is in the data directory under the application data directory, and the configuration method is described in the banbot official documentation, https://www.banbot.site.