lzc-sdk-version: 0.1
name: Obsidian
package: ink.akawa.ety001.obsidian
version: 1.8.10
description: The free and flexible app for your private thoughts.
license: https://docs.obsidian.md/Developer+policies
homepage: https://obsidian.md/
author: Obsidian
min_os_version: 1.3.8
application:
  subdomain: obsidian
  background_task: true
  multi_instance: true
  gpu_accel: true
  usb_accel: true
  ingress:
    - protocol: tcp
      port: 22
      service: obsidian
  routes:
    - /=http://obsidian.ink.akawa.ety001.obsidian.lzcapp:10000
services:
  obsidian:
    # ety001/obsidian:ubuntu-noble
    image: registry.lazycat.cloud/ety001/ety001/obsidian:aba64c121d62074c
    shm_size: "512m"
    tmpfs:
      - /run
    environment:
      - XDG_RUNTIME_DIR=/run/user/1001
    binds:
      - /lzcapp/var/home:/home/lzc
      - /lzcapp/var/home_ssh:/home/lzc/.ssh
      - /lzcapp/var/home_config:/home/lzc/.config
      - /lzcapp/cache/home_cache:/home/lzc/.cache
      - /lzcapp/cache/supervisor:/var/log/supervisor
    setup_script: /lzcapp/pkg/content/init.sh
locales:
  zh:
    description: "免费且灵活的私人思考应用。"
  zh_CN:
    description: "免费且灵活的私人思考应用。"
  en:
    description: "The free and flexible app for your private thoughts."