lzc-sdk-version: 0.1
name: AuthSteem
package: ink.akawa.ety001.authsteem
version: 0.0.1
description: An offline sign program for Steem Blockchain.
license: https://github.com/steemfans/authsteem#MIT-1-ov-file
homepage: https://github.com/steemfans/authsteem
author: ETY001
min_os_version: 1.3.0
application:
  subdomain: authsteem
  background_task: false
  multi_instance: true
  routes:
    - /=http://authsteem.ink.akawa.ety001.authsteem.lzcapp
services:
  authsteem:
    image: registry.lazycat.cloud/ety001/ety001/filezilla:061b39fc697b02c0
    environment:
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
      - NO_FULL=1
      - FM_HOME=/home/${LAZYCAT_APP_DEPLOY_UID}
    binds:
      - /lzcapp/var/config:/config
locales:
  zh:
    description: "一款 Steem 区块链离线签名程序"
  zh_CN:
    description: "一款 Steem 区块链离线签名程序"
  en:
    description: "An offline sign program for Steem Blockchain"