lzc-sdk-version: 0.1
name: AuthSteem
package: ink.akawa.ety001.authsteem
version: 0.0.2
description: An offline sign program for Steem Blockchain.
license: https://github.com/steemfans/authsteem#MIT-1-ov-file
homepage: https://github.com/steemfans/authsteem
author: ETY001
min_os_version: 1.3.0
application:
  subdomain: authsteem
  background_task: false
  multi_instance: true
  routes:
    - /=http://authsteem:5000
services:
  authsteem:
    # ety001/authsteem-for-lazycat:edge
    image: registry.lazycat.cloud/ety001/ety001/authsteem-for-lazycat:4a8fd1d40ceba5fb
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/db:/app/db
locales:
  zh:
    description: "一款 Steem 区块链离线签名程序"
  zh_CN:
    description: "一款 Steem 区块链离线签名程序"
  en:
    description: "An offline sign program for Steem Blockchain"