ext_config:
  enable_document_access: true
  enable_media_access: true
application:
  subdomain: ettools
  background_task: true
  multi_instance: false
  routes:
    - /=http://ettools.ink.akawa.ety001.ettools.lzcapp:3000
  injects:
    - id: open-save-chooser
      on: browser
      when:
        - /*
      do:
        - src: file:///lzcapp/pkg/content/lazycat-injects/lzc-file-chooser-inject.js
          params:
            locale: auto
            hooks:
              fileSystemAccess: true
              fileInput: true
services:
  ettools:
    image: registry.lazycat.cloud/ety001/ety001/et-tools:cb23fdc124553b6e
