lzc-sdk-version: 0.1
name: Gogs
package: ink.akawa.ety001.gogs
version: 0.0.1
description: Gogs is a painless self-hosted Git service. It is similar to GitHub, Bitbucket, and GitLab, but is an open source lightweight solution written in Go.
license: https://github.com/gogs/gogs/blob/main/LICENSE
homepage: https://gogs.io/
author: gogs
min_os_version: 1.3.0
application:
  subdomain: gogs
  background_task: true
  multi_instance: false
  ingress:
    - protocol: tcp
      port: 22
      service: gogs
    - protocol: tcp
      description: MySQL
      port: 3306
      service: mysql
  routes:
    - /=http://gogs.ink.akawa.ety001.gogs.lzcapp:3000
services:
  mysql:
    image: registry.lazycat.cloud/mysql
    binds:
      - /lzcapp/var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=123456
    health_check:
      test:
        - CMD-SHELL
        - mysqladmin ping -hlocalhost -ugogs -p123456
      start_period: 60s
      disable: false
  gogs:
    image: registry.lazycat.cloud/ety001/gogs/gogs:3f71502d7848ab2e
    depends_on:
      - mysql
    environment:
      - TZ=Asia/Shanghai
      - RUN_CROND=1
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/crontabs/periodic:/etc/periodic
    setup_script: |
      if [ ! -d "/data/gogs/log" ]; then
        mkdir -p /data/gogs/log && chmod 777 /data/gogs/log
      fi
locales:
  zh:
    description: "Gogs 是一个无痛的自托管 Git 服务。它类似于 GitHub、Bitbucket 和 GitLab，但是一个用 Go 编写的开源轻量级解决方案。"
  zh_CN:
    description: "Gogs 是一个无痛的自托管 Git 服务。它类似于 GitHub、Bitbucket 和 GitLab，但是一个用 Go 编写的开源轻量级解决方案。"
  en:
    description: "Gogs is a painless self-hosted Git service. It is similar to GitHub, Bitbucket, and GitLab, but is an open source lightweight solution written in Go."

